version: "3"
services:

  mongo:
    image: mongo:3.3
    volumes:
        - ./mymongodb:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: 300M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
      placement:
         constraints: [node.role == manager]

    ports:
      - "27017:27017"
    networks:
      - webnet


  backend:
    # replace username/repo:tag with your name and image details
    image: hub.kloc-apps.com/helpdeskbackend:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
      update_config:
          parallelism: 1
          delay: 10s
          failure_action: rollback
      placement:
         constraints: [node.role == manager]

    ports:
      - "3001:3000"
    networks:
      - webnet


  frontclient:
    # replace username/repo:tag with your name and image details
    image: hub.kloc-apps.com/helpdeskclient:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
          parallelism: 1
          delay: 10s
          failure_action: rollback
      placement:
         constraints: [node.role == manager]
    ports:
      - "80:80"

    networks:
      - webnet

networks:
  webnet:
